from fpdf import FPDF
import os

BASE_DIR = os.path.dirname(__file__)
FONT_PATH = os.path.join(BASE_DIR, "NotoSans-Regular.ttf")

class MedSaathiPDF(FPDF):
    def __init__(self):
        super().__init__()
        if os.path.exists(FONT_PATH):
            self.add_font('NotoSans', '', FONT_PATH, uni=True)

    def header(self):
        self.set_font('NotoSans', size=18)
        self.set_text_color(29, 158, 117)
        self.cell(0, 15, 'MedSaathi - Medical Report Summary', align='C', new_x='LMARGIN', new_y='NEXT')
        self.set_font('NotoSans', size=11)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, 'Simple Health Report in Your Language', align='C', new_x='LMARGIN', new_y='NEXT')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('NotoSans', size=8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, 'Generated by MedSaathi | For informational purposes only', align='C')


def generate_pdf(summary_text, language='English', output_path='medsaathi_report.pdf'):
    pdf = MedSaathiPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font('NotoSans', size=13)
    pdf.set_text_color(29, 158, 117)
    pdf.cell(0, 10, f'Language: {language}', ln=True)
    pdf.ln(8)

    pdf.set_font('NotoSans', size=11)
    pdf.set_text_color(40, 40, 40)

    clean_text = summary_text.replace('✅', '[Normal] ').replace('⚠️', '[High] ').replace('🔴', '[Low] ')

    for line in clean_text.split('\n'):
        if line.strip():
            pdf.multi_cell(0, 8, line.strip())
            pdf.ln(4)

    pdf.output(output_path)
    return output_path